// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaVbOT_CigfECd3bz-OyR3wO0hNXvp-cY',
    appId: '1:62797404098:web:d17078208e7a92cf10285b',
    messagingSenderId: '62797404098',
    projectId: 'ecommerce-4b8bd',
    authDomain: 'ecommerce-4b8bd.firebaseapp.com',
    storageBucket: 'ecommerce-4b8bd.appspot.com',
    measurementId: 'G-LKWXY38P78',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuxS7a2GCxDsKZSwwFLfUde5Jtuy0duxo',
    appId: '1:62797404098:android:6ce99337a90d948b10285b',
    messagingSenderId: '62797404098',
    projectId: 'ecommerce-4b8bd',
    storageBucket: 'ecommerce-4b8bd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBk7qQM5RFplPkFTXyEH8Tsp_SSemHqvUg',
    appId: '1:62797404098:ios:a20212cc30d8ca2710285b',
    messagingSenderId: '62797404098',
    projectId: 'ecommerce-4b8bd',
    storageBucket: 'ecommerce-4b8bd.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBk7qQM5RFplPkFTXyEH8Tsp_SSemHqvUg',
    appId: '1:62797404098:ios:a20212cc30d8ca2710285b',
    messagingSenderId: '62797404098',
    projectId: 'ecommerce-4b8bd',
    storageBucket: 'ecommerce-4b8bd.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaVbOT_CigfECd3bz-OyR3wO0hNXvp-cY',
    appId: '1:62797404098:web:724ad9d59f7f2c4b10285b',
    messagingSenderId: '62797404098',
    projectId: 'ecommerce-4b8bd',
    authDomain: 'ecommerce-4b8bd.firebaseapp.com',
    storageBucket: 'ecommerce-4b8bd.appspot.com',
    measurementId: 'G-CVVYFYJVZ2',
  );
}
